### PR TITLE
Would you please turn on the issue?

### PR DESCRIPTION
**Pull request by koumaza**
In my environment, this Kernel doesn't start.
I'd like to solve it with **[Issue](https://github.com/nathanchance/WSL2-Linux-Kernel/issues)**.
Thanks.

### CODE REVIEW

**Comment by nathanchance** [comment]
I provide this kernel with no sort of support, hence no issues. There is no easy way for me to debug things. Sorry that it does not work for you.

**Comment by koumaza** [comment]
That's okay. Thank you so much.
I left [dmesg](https://gist.github.com/koumaza/6c82546c7aeac5ad6ab52496a0ede6de).

**Comment by Justsnoopy30** [comment]
Your recent builds won't mount the C drive. A build from a few months ago was working.
On login to WSL2 Ubuntu:
`An error occurred mounting one of your file systems. Please run 'dmesg' for more details.`

Relevant dmesg:
```[    3.918582] swapon: swapfile has holes
[    3.918674] ERROR: CreateSwap:819: swapon failed 22
[    4.850918] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    4.851842] sd 0:0:0:1: Attached scsi generic sg1 type 0
[    4.853434] sd 0:0:0:1: [sdb] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    4.853435] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[    4.853567] sd 0:0:0:1: [sdb] Write Protect is off
[    4.853579] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 00 00
[    4.853835] sd 0:0:0:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    4.879586] sd 0:0:0:1: [sdb] Attached SCSI disk
[    5.004852] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    5.418252] 9pnet: Could not find request transport: virtio
[    5.418259] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=1000;gid=1000;symlinkroot=/mnt/
[    5.418261] ) failed: 22
[    5.455104] init: (7) ERROR: CreateProcessParseCommon:871: Failed to translate C:\Users\evere

[    5.455184] init: (7) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32

[    5.455240] init: (7) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows
[    5.455371] init: (7) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32\wbem

[    5.455451] init: (7) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Windows\System32\WindowsPowerShell\v1.0\```

**Comment by nathanchance** [comment]
@Justsnoopy30 can you please file an issue (I have opened them up) with a full dmesg?

Would you be willing to test a bunch of kernels to narrow down the issue for me?

**Comment by nathanchance** [comment]
@Justsnoopy30 also, please include your `.wslconfig`.

**Comment by koumaza** [comment]
In my case it doesn't work with recent versions.
~~It's not working since at least v27.~~ Not working on v25~v30
Is this `.wslconfig` bad?
<details><summary>.wslconfig</summary>

```config
[WSL2]
kernel="C:\\Users\\satori\\scoop\\apps\\wsl2-next\\current\\bzImage"
```
</details>

#### For v30
It seems that the `drvfs` mount failed.
<details><summary>Excerpt log</summary>

```console
[    3.550951] swapon: swapfile has holes
[    3.551028] ERROR: CreateSwap:819: swapon failed 22
[    4.019326] scsi 0:0:0:1: Direct-Access     Msft     Virtual Disk     1.0  PQ: 0 ANSI: 5
[    4.020023] sd 0:0:0:1: Attached scsi generic sg1 type 0
[    4.021240] sd 0:0:0:1: [sdb] 536870912 512-byte logical blocks: (275 GB/256 GiB)
[    4.021241] sd 0:0:0:1: [sdb] 4096-byte physical blocks
[    4.021428] sd 0:0:0:1: [sdb] Write Protect is off
[    4.021429] sd 0:0:0:1: [sdb] Mode Sense: 0f 00 00 00
[    4.021623] sd 0:0:0:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    4.025624] sd 0:0:0:1: [sdb] Attached SCSI disk
[    4.049227] EXT4-fs (sdb): mounted filesystem with ordered data mode. Opts: discard,errors=remount-ro,data=ordered
[    4.103268] 9pnet: Could not find request transport: virtio
[    4.103275] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/c (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=C:\;uid=0;gid=0;symlinkroot=/mnt/
[    4.103276] ) failed: 22
[    4.103290] 9pnet: Could not find request transport: virtio
[    4.103293] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/v (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=V:\;uid=0;gid=0;symlinkroot=/mnt/
[    4.103294] ) failed: 22
[    4.103304] 9pnet: Could not find request transport: virtio
[    4.103307] init: (1) ERROR: MountPlan9WithRetry:282: mount drvfs on /mnt/z (cache=mmap,noatime,msize=262144,trans=virtio,aname=drvfs;path=Z:\;uid=0;gid=0;symlinkroot=/mnt/
[    4.103308] ) failed: 22
[    4.123674] init: (7) ERROR: CreateProcessParseCommon:871: Failed to translate C:\Users\satori

[    4.123745] init: (7) ERROR: UtilTranslatePathList:2721: Failed to translate C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler
```
</details>

Full log html: [v30-wsl2_arch-dmesg.html.gz](https://github.com/nathanchance/WSL2-Linux-Kernel/files/4772182/v30-wsl2_arch-dmesg.html.gz)

**Comment by Justsnoopy30** [comment]
Alright.

**Pull request closed without merging**
